### ISSUE TITLE
Project initial todo list

### ISSUE THREAD

**Issue by soobinrho** [soobinrho/freebsd-src#1]
July 5, 2023

- [x] For integrating mfsBSD into the release building tools, using git clone as the main approach is not viable.
People might not be able to use git, and internet access may not be available.
Instead, pull mfsBSD as a snapshot into `usr/src/contrib` or `usr/src/release/scripts` and then create a Makefile under `usr/src/release` to build an mfsBSD image.

- There are a lot of architectures in the release engineering.
So, mfsBSD building will have to be tested against all of these architectures.

- Once we're done with the coding, we'll have a meeting with re@ team (release engineering team) to get feedback.

- `git pull -- rebase` and `git push -f`

June 12, 2023

- [x] Definitely try running `make release` to build all the images available to get a sense of how it works.

- [x] When they make release, they put it on the release website.
In this project, my aim should be to push mfsBSD as one of the images listed there.
Also, in the main Makefile, as a comment, there's a mention of "user-driven targets such as memstick, dvd, etc.
After the code is complete, send the commit link to my mentors so that they can review it, before I make an actual pull request to the src repository.

- [x] Fill in the milestones in the wiki page.

June 27, 2023

- [x] Status report PR done.
Based on the status report template file.
Created a fork of the src repository and of course created a feature branch with the name of mfsBSD building integration.
Also added this link to our main wiki GSoC project page.

- [x] Migrate and connect, introduce target mfsBSD, and make a bootable mfsBSD image.

- [x] If you see `usr/src/release` Makefiles, there are files like Makefile.azure.
Theses are because they are too different if they were to be at the top level Makefile.
So, my mentors' recommendation is to create `Makefile.mfsbsd`.

- [x] See how the top level Makefile interacts with specific smaller Makefiles.
Get a grasp of how FreeBSD Makefiles do.
Try making ec2 images with `Makefile.ec2`.

- [x] Developments are carried out in current branch's main.
Then, they are migrated to stable and release.

- [x] Create my own feature branch.

- [x] Read `man make(1)` from FreeBSD

- [x] Rebase regularly on the main branch.

- [x] Night before my weekly meeting on Monday's, email my mentors to let them know what's going on, and let them know if I want the meeting or not.

```
If your work is included in any of the FreeBSD repositories or upstreamed to other projects,
please consider giving recognition to the GSoC program by adding the line below to your commit logs.
Sponsored by: Google, Inc. (GSoC 2023)
```

**Comment by soobinrho** [comment]
Note: The major distinction between mfsBSD and memstick images is that mfsBSD runs entirely on mfs (memory file system). What this means is that you can install an mfsBSD image on a USB or even a hard drive, and after you boot into mfsBSD, however, everything is now loaded into mfs, which means you can even unplug the USB or delete the portion of the hard drive that mfsBSD was installed in. The original medium - USB, hard drive, or whatever - can be modified or even unplugged after booting into mfsBSD. Beautiful!

**Comment by soobinrho** [comment]
mfsBSD white paper: https://people.freebsd.org/~mm/mfsbsd/mfsbsd.pdf
mfsBSD repository: https://github.com/mmatuska/mfsbsd
mfsBSD website: https://mfsbsd.vx.sk/
mfsBSD remote installation: https://docs.freebsd.org/en/articles/remote-install/
mfsBSD remote installation (forum): https://forums.freebsd.org/threads/how-to-install-freebsd-w-zfs-on-a-remote-server-from-a-linux-rescue-system.61842/#post-356621

mfsBSD 2010 presentation video: https://www.youtube.com/watch?v=ebhxZt7BbbA

mfsBSD 2012 presentation video: https://youtu.be/jClKvKUBBIc
mfsBDS 2012 presentation slides: https://people.freebsd.org/~pgj/bsdday2012/materials/07_mfsbsd.pdf

mfsBSD 2014 presentation video: https://www.youtube.com/watch?v=nb8jB5x0OX4

**Comment by soobinrho** [comment]
- [ ] Add https://man.freebsd.org/cgi/man.cgi?query=hier&sektion=7&format=html

**Comment by soobinrho** [comment]
NOTES
- Copied mfsBSD repository to `contrib/mfsbsd` folder.
- Deleted `contrib/mfsbsd/.git` folder to avoid conflict.

**Comment by soobinrho** [comment]
- Integrate mfsBSD into the main release Makefile's clean target.

**Comment by soobinrho** [comment]
- In the final PR, add this note: The structure and the style of the code was taken from the existing `release/Makefile.vm` to make the code more maintanable in the future.

Also, change the commit author to soobinrho@FreeBSD.org

**Comment by soobinrho** [comment]
- [x] Use make -V {variable name} such as `make ${MAKE_FLAGS} -C /usr/src/release -V WORLDDIR` to see the value of the variable.

**Comment by soobinrho** [comment]
- Add mfsBSD entries to `release.sh` and `release.conf.sample`.

**Comment by soobinrho** [comment]
- Final commit message should be something like 

```
release: Import mfsBSD <Username/Repository@SHA>

Full explanation with detailed context.
```

e.g. mmatuska/mfsbsd@0da8061

For more information: https://docs.freebsd.org/en/articles/committers-guide/#git-primer

**Comment by soobinrho** [comment]
- Difference between .iso files and .img files: https://lists.freebsd.org/pipermail/freebsd-questions/2013-May/250811.html
- DVD / DISK images (.iso files) cannot be used on non-opticals. Only use .img files for SSD's or memsticks.
Source: https://forums.freebsd.org/threads/is-it-possible-to-convert-a-bootable-iso-to-a-bootable-ssd.44129/

**Comment by soobinrho** [comment]
```
# A usual workflow for buildworld and buildkernel
cd /usr/src
time make -j24 buildworld >& buildworld.log
time make -j24 buildkernel >& buildkernel.log
```

Source: https://forums.freebsd.org/threads/whats-your-fastest-buildworld-time.84658/

**Comment by soobinrho** [comment]
```
# Creating a shared drive between Windows and FreeBSD
# 1. [On Windows WSL,] `lsblk` to find the drive name.
# 2. `fdisk /dev/<drive name>` to make a GPT partition table and a partition.
# 3. `mkfs.ext4 /dev/<drive partition name>` to format the partition as ext4.
# 4. `mkdir /mnt/<shared partition folder name> && mount /dev/<drive partition name> /mnt/<shared partition folder name>` to move the files that need to be shared. 
# 5. [On FreeBSD] `geom disk list` to find the partition name.
# 6. `mkdir /<shared partition folder name>` to create a folder for the partition to be mounted at.
# 7. Add the following entry to `/etc/fstab` to automatically mount the shared partition on boot:
#    /dev/<drive partition name>    /<shared partition folder name>    ext2fs    rw    0    0
```

Source: https://man.freebsd.org/cgi/man.cgi?fstab(5)

**Comment by soobinrho** [comment]
```
# If bsdinstall can't find base.txz and kernel.txz:
As a workaround, I always place the *.txz archives and the MANIFEST manually into /usr/freebsd-dist/ on the running system, before running bsdinstall. It works this way.
```

Source: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213488

**Comment by soobinrho** [comment]
```
# How to make base.txz and kernel.txz
make release would create all the distfiles {base,base-dbg,kernel,kernel-dbg,lib32,lib32-dbg,ports,src,tests}.txz, and all the installation images (*.iso, *.img).

If you want only base and kernel and if this is a unpatched RELEASE, kernel.txz and base.txz can be download from https://download.freebsd.org/, for example https://download.freebsd.org/releases/amd64/13.1-RELEASE/.

If this is a patched RELEASE (or STABLE, CURRENT) and have a system source buildworld and buildkernel already run:
cd /usr/src/release
make kernel.txz base.txz
```

Source: https://forums.freebsd.org/threads/creating-txz-files.85303/

**Comment by soobinrho** [comment]
```
# Where is pkg-static?
It looks like it's a part of the pkg port.
```

Source: https://forums.freebsd.org/threads/pkg-vs-pkg-static.61710

Also, it seems like a fresh instal of FreeBSD doesn't contain pkg-static. When we first run pkg, it asks to initialize and then installs pkg-static. This, however, seems to require internet connection, which means pkg-static may not be available to users without internet access.

**Comment by soobinrho** [comment]
- [x] When vendor importing, use whitespace for formatting. For example:

```
Changelog:      https://git.tcpdump.org/tcpdump/blob/55bc126b0216cfe409b8d6bd378f65679d136ddf:/CHANGES
Reviewed by:    emaste
Obtained from:  https://www.tcpdump.org/release/tcpdump-4.99.4.tar.gz
Sponsored by:   The FreeBSD Foundation
```
Source: https://github.com/freebsd/freebsd-src/commit/ee67461e56828dd1f8de165947ba83f6d9148a87

In my case, `Obtained from:` will be `Obtained from: https://github.com/mmatuska/mfsbsd/commit/0da806178042b0d3cd20fb6b2e6e38a338a24b9c`

**Comment by soobinrho** [comment]
- [x] Add `WITH_MFSBSD` entry to https://github.com/freebsd/freebsd-src/blob/main/release/release.sh and https://github.com/freebsd/freebsd-src/blob/main/release/release.conf.sample

**Comment by soobinrho** [comment]
- [x] Add `mfsbsd-install` target based on `relase-install` and `vm-install`. Note that the entire target executes only `.if defined(DESTDIR) && !empty(DESTDIR)`.

- [x] Add an entry on the comments on the top of `release/Makefile`: `install: Invokes the release-install, vm-install, and mfsbsd-install targets` and `mfsbsd-install: Copies all mfsBSD images into ${DESTDIR}`

- [x] Add `mfsbsd-base` target to `Makefile.mfsbsd`
```
mfsbsd-base:	mfsbsd-image
```

- [x]  Add `mfsbsd-image` target to `Makefile.mfsbsd`
```
mfsbsd-image:
.if defined(WITH_MFSBSD) && !empty(WITH_MFSBSD)
	${MAKE} -C ${.CURDIR} ${.MAKEFLAGS} ${MFSBSD_TARGETS}
.endif
...
mfsbsd-release:
.if defined(WITH_MFSBSD) && !empty(WITH_MFSBSD)
	${MAKE} -C ${.CURDIR} ${.MAKEFLAGS} mfsbsd-image
.endif
```

- [x]  Also, change the order of the targets in `Makefile.mfsbsd` to be consistent with `release/Makefile.vm`:
```
mfsbsd-base:	mfsbsd-image
mfsbsd-image:
	...
list-mfsbsd:
	...
mfsbsd-install:
	...
mfsbsd-release:
	...
```

**Comment by soobinrho** [comment]
- [x] Add the following entry to https://github.com/freebsd/freebsd-src/blob/main/share/man/man7/release.7

```
.Sh MFSBSD IMAGES
The following 
.Fa release.conf
variables are relevant only to mfsBSD image builds:
.Bl -tag -width Ev
.It Va WITH_MFSBSD
Set to a non-null value to build mfsBSD images as part of the release build.
.Va WITH_VMIMAGES
may also be specified as an environment variable passed to
.Xr make 1 .
.El
.Pp
Additionally, the
.Va WITH_MFSBSD
variable can be added to
.Pa release.conf ,
and used in conjunction with
.Pa release.sh .
.Pp
For a list of supported
.Va CLOUDWARE
values, run:
.Bd -literal -offset indent
cd /usr/src
make -C release list-mfsbsd
.Ed
```

- [x] Also add `mfsbsd-image` entry under the `MAKEFILE TARGETS` section

```
.It Cm mfsbsd-image
Creates mfsBSD images in various formats.
The
.Cm mfsbsd-image
target requires the
.Va WITH_MFSBSD
.Xr make 1
environment variable to be set to a non-null value.
```

- [x] At the same section, add `list-mfsbsd`:

```
.It Cm list-mfsbsd
Displays the list of valid
.Va MFSBSD_TARGETS
values.
```

- [x] Add an entry to the `FILES` section:

```
.It Pa /usr/src/release/Makefile
.It Pa /usr/src/release/Makefile.mfsbsd
.It Pa /usr/src/release/Makefile.vm
```

- [x] Create `list-mfsbsd` target at `Makefile.mfsbsd`:

```
list-mfsbsd:
	@${ECHO}
	@${ECHO} "Supported mfsBSD images:"
.for TARGET in ${MFSBSD_TARGETS}
	@${ECHO} "  ${TARGET}: ${${TARGET}_DESC}"
.endfor
```

- [x] Test the final man page using
```bash
cd /usr/share/man/man7
gzip release.7
man 7 release
```

**Comment by soobinrho** [comment]
- [x] Add `CLEANFILES+=` to `Makefile.mfsbsd` based on: 
```sh
CLEANFILES=	packagesystem *.txz MANIFEST release ${IMAGES}
.if defined(WITH_COMPRESSED_IMAGES) && !empty(WITH_COMPRESSED_IMAGES)
. for I in ${IMAGES}
CLEANFILES+=	${I}.xz
. endfor
.endif
.if defined(WITH_DVD) && !empty(WITH_DVD)
CLEANFILES+=	pkg-stage
.endif
```
Source: `release/Makefile`

Explanation: https://github.com/freebsd/freebsd-src/blob/main/share/mk/bsd.obj.mk is included in `release/Makefile` and this includes:
```
# +++ targets +++
#
#	clean:
#		remove ${CLEANFILES}; remove ${CLEANDIRS} and all contents.
#
#	cleandir:
#		remove the build directory (and all its contents) created by obj
#
```

- [x] Test run `cd /usr/src/release make clean`.

**Comment by soobinrho** [comment]
> Try `make -V .CURDIR` and then temporarily add `pwd >> /usr/src/release/1.log`, `echo ".CURDIR=${.CURDIR} | .OBJDIR=${.OBJDIR}" >> /usr/src/release/1.log` to `release/Makefile` to see where it's executing from. My question is: the build process creates `${DISTDIR}` and then puts all the image files there, but where exactly is it? Hypothesis: `/usr/obj/.../release`. Running the debug commands above will help me better understand.

> Also, try `ls -d -1 "$PWD/"*.* >> /usr/src/release/1.log` at both the `base.txz` target and `kernel.txz` target.

> After gaining a better understanding, implement the same `${DISTDIR}` structure for `Makefile.mfsbsd` and test using `... >> /usr/src/release/1.log` to see if both the `release/Makefile` and `release/Makefile.mfsbsd` have the same `${DISTDIR}`.

- [x] Update: `.CURDIR` shows `/usr/src/release`, while `PWD` shows `/usr/obj/usr/src/amd64.amd64/release`. Thus, I am going to implement the same DESTDIR structure for all of the mfsbsd image targets.

**Comment by soobinrho** [comment]
Make two Phabricator revisions. First, request for a pre-commit review for the mfsBSD import. After it's been approved, request for the other commit.

-- update: `git-arc` seems to solve this problem. No need to create two separate revisions.

**Comment by soobinrho** [comment]
- [x] Test run
```bash
cd /usr/src
make -C release list-mfsbsd

# cd /usr/src/release && make list-mfsbsd works for sure. The above, however, needs testing
```

- [x] Test run release.sh and release.conf.sample.
```sh
# How I ran the test
cd /usr/src/release
cp -r /usr/src /scratch/usr/
env SRC_UPDATE_SKIP=1 ./release.sh -c ./release.conf >& ./1.log
```

**Comment by soobinrho** [comment]
- [x] Instead of `env ... make ...`, use the built-in function `make ... <environmental variables>...`.
- [x] To insert shell commands, use `MFSBSD_DIR!=    realpath ${WORLDDIR} ...`. In this case, remove MFSBSD_DIR entry from `release.7`.
- [x] Instead of `cd ... && make ...`, use the built-in function `make -C <dir>`
- [x] Use the debugging flags: `make -d AFstdout` prints all debugging invormation to stdout. Also, `make -V .MAKE.EXPORTED` to see all variables exported by Make.
- [x] Insert `echo "MAKEFLAGS=${MAKEFLAGS}" && echo ".MAKE.EXPORTED=${.MAKE.EXPORTED}"` inside `mfsbsd/Makefile` to debug.
- [x] Comment out all build parts from `release.sh` and instead have them do `make -N mfsbsd-image` and `make -V MAKEFLAGS` and `make -V .MAKE.EXPORTED`. First time running original `release.sh` resulted in mfsBSD having an issue with gpart. Gotta find out if all the environmental values are working as intended.
- [x] Test if `make ... .OBJDIR=${MFSBSD_DIR}` actually works as intended. It might be the case it's overridden by another value. If such a case is true, then gotta pass `make ... MAKEOBJDIR=${MFSBSD_DIR}` instead. If required, reference https://man.freebsd.org/cgi/man.cgi?make(1)
- [x] Also add commit hash to the commit message (tested as of August 17, 2023, commit ...)
- [x] Remove `.cirrus.yml` at mfsBSD import commit to prevent collision with `/usr/src/.cirrus.yml`. Add this to the import commit message too.
- [x] I think one reason my code didn't work with `release/release.sh` is because mfsBSD calls the following:
```sh
#mfsbsd/tools/do_gpt.sh
...
dd of=${FSIMG} if=/dev/zero count=${IMG_SIZE} bs=1k
dd of=${TMPIMG} if=/dev/zero count=${FSSIZE} bs=1k
...
  ${TIME} dd if=${EFIIMG} of=/dev/${unit}p2 bs=128k
```
The problem might be that when `release.sh` calls `chroot`, there's no `/dev` folder and no `/dev/zero` as well. To remediate, I'll check if `/dev` exists, and if not, create one -- same goes for `/dev/zero`.
Update: `release.sh` already creates `${CHROOTDIR}/dev` folder. Thus, it might be a good idea to create a hard link to `/dev/zero` by using `ln /dev/zero ${CHROOTDIR}/dev/zero`
Update: `release.sh` already does `mount -t devfs devfs ${CHROOTDIR}/dev` so creating a link of `/dev/zero` should be unnecessary.

**Comment by soobinrho** [comment]
Completed. https://wiki.freebsd.org/SummerOfCode2023Projects/IntegrateMfsBSDIntoTheReleaseBuildingTools
